/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package QATracker.view;

import QATracker.domain.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Michelle
 */
public class CrearUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearUsuario
     */
    public CrearUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombreUsuario = new javax.swing.JLabel();
        lbPuesto = new javax.swing.JLabel();
        lbContrasena = new javax.swing.JLabel();
        btCrear = new javax.swing.JButton();
        txtNombreUsuario = new javax.swing.JTextField();
        txtPuesto = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JTextField();

        lbNombreUsuario.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lbNombreUsuario.setForeground(new java.awt.Color(0, 51, 255));
        lbNombreUsuario.setText("Nombre Usuario:");

        lbPuesto.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lbPuesto.setForeground(new java.awt.Color(0, 51, 255));
        lbPuesto.setText("Puesto:");

        lbContrasena.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lbContrasena.setForeground(new java.awt.Color(0, 51, 255));
        lbContrasena.setText("Contrasena:");

        btCrear.setText("Crear");
        btCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreUsuario)
                    .addComponent(lbPuesto)
                    .addComponent(lbContrasena))
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(txtPuesto)
                    .addComponent(txtNombreUsuario))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCrear)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombreUsuario)
                    .addComponent(txtNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPuesto)
                    .addComponent(txtPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContrasena)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btCrear)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCrearActionPerformed
        try {
            Usuario usuario= new Usuario();
            usuario.setDescripcionUsuario(txtNombreUsuario.getText());
            usuario.setPuesto(txtPuesto.getText());
            usuario.setClave(txtContrasena.getText());
            usuario.setEstadoUsuario(1);
            QATracker.usuarioBus.crear(usuario);
            JOptionPane.showMessageDialog(rootPane, "El usuario ha sido creado.", "Exito", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_btCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCrear;
    private javax.swing.JLabel lbContrasena;
    private javax.swing.JLabel lbNombreUsuario;
    private javax.swing.JLabel lbPuesto;
    private javax.swing.JTextField txtContrasena;
    private javax.swing.JTextField txtNombreUsuario;
    private javax.swing.JTextField txtPuesto;
    // End of variables declaration//GEN-END:variables
}
