/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package QATracker.view;

import QATracker.business.IssueBusiness;
import QATracker.business.ProyectoBusiness;
import QATracker.business.TareaBusiness;
import QATracker.business.UsuarioBusiness;
import QATracker.domain.Usuario;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JMenu;
import javax.swing.JOptionPane;

/**
 *
 * @author Michelle
 */
public class QATracker extends javax.swing.JFrame {

    /**
     * Creates new form QATracker
     */
    public static UsuarioBusiness usuarioBus;
    public static ProyectoBusiness proyectoBus;
    public static TareaBusiness tareaBus;
    public static IssueBusiness issueBus;
    public QATracker() throws SQLException {
        initComponents();
        this.usuarioBus= new UsuarioBusiness();
        this.proyectoBus= new ProyectoBusiness();
        this.tareaBus= new TareaBusiness();
        this.issueBus= new IssueBusiness();
        menuSesion.setVisible(false);
        menuItemSettings.setVisible(false);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        menuBar1 = new javax.swing.JMenuBar();
        menuStart = new javax.swing.JMenu();
        menuItemLogInInicio = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        menuItemNewUser = new javax.swing.JMenuItem();
        menuItemSettings = new javax.swing.JMenuItem();
        menuItemSignOutInicio = new javax.swing.JMenuItem();
        menuItemExit = new javax.swing.JMenuItem();
        menuProyectos = new javax.swing.JMenu();
        menuItemConsultaProyectos = new javax.swing.JMenuItem();
        menuMantenimientoProyectos = new javax.swing.JMenu();
        menuItemActualizrMantenimientoProyectos = new javax.swing.JMenuItem();
        menuItemBorrarMantenimientoProyectos = new javax.swing.JMenuItem();
        menuItemCrearMantenimientoProyectos = new javax.swing.JMenuItem();
        menuTareas = new javax.swing.JMenu();
        menuItemConsultaTareas = new javax.swing.JMenuItem();
        menuMantenimientoTareas = new javax.swing.JMenu();
        menuItemActualizarMantenimientoTareas = new javax.swing.JMenuItem();
        menuItemCrearMantenimientoTareas = new javax.swing.JMenuItem();
        menuItemRenombrarMantenimientoTareas = new javax.swing.JMenuItem();
        menuIssues = new javax.swing.JMenu();
        menuItemConsultaIssues = new javax.swing.JMenuItem();
        menuMantenimientoIssues = new javax.swing.JMenu();
        menuItemActualizarMantenimientoIssues = new javax.swing.JMenuItem();
        menuItemCrearMantenimientoIssues = new javax.swing.JMenuItem();
        menuSesion = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1020, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 977, Short.MAX_VALUE)
        );

        menuStart.setText("Start");

        menuItemLogInInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550291_secure-server-px-png.png"))); // NOI18N
        menuItemLogInInicio.setText("Log in");
        menuItemLogInInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemLogInInicioActionPerformed(evt);
            }
        });
        menuStart.add(menuItemLogInInicio);

        menuUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397545848_Manager.png"))); // NOI18N
        menuUser.setText("User");

        menuItemNewUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397533314_plus_add_blue.png"))); // NOI18N
        menuItemNewUser.setText("New User");
        menuItemNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNewUserActionPerformed(evt);
            }
        });
        menuUser.add(menuItemNewUser);

        menuItemSettings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550416_maintenance.png"))); // NOI18N
        menuItemSettings.setText("Settings");
        menuItemSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSettingsActionPerformed(evt);
            }
        });
        menuUser.add(menuItemSettings);

        menuStart.add(menuUser);

        menuItemSignOutInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550521_Log Out.png"))); // NOI18N
        menuItemSignOutInicio.setText("Sign out");
        menuItemSignOutInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemSignOutInicioActionPerformed(evt);
            }
        });
        menuStart.add(menuItemSignOutInicio);

        menuItemExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550566_exit.png"))); // NOI18N
        menuItemExit.setText("Exit");
        menuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemExitActionPerformed(evt);
            }
        });
        menuStart.add(menuItemExit);

        menuBar1.add(menuStart);

        menuProyectos.setText("Proyectos");

        menuItemConsultaProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397543922_xmag.png"))); // NOI18N
        menuItemConsultaProyectos.setText("Consulta");
        menuItemConsultaProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaProyectosActionPerformed(evt);
            }
        });
        menuProyectos.add(menuItemConsultaProyectos);

        menuMantenimientoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550416_maintenance.png"))); // NOI18N
        menuMantenimientoProyectos.setText("Mantenimiento");

        menuItemActualizrMantenimientoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397534265_earth_internet_reload.png"))); // NOI18N
        menuItemActualizrMantenimientoProyectos.setText("Actualizar");
        menuItemActualizrMantenimientoProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizrMantenimientoProyectosActionPerformed(evt);
            }
        });
        menuMantenimientoProyectos.add(menuItemActualizrMantenimientoProyectos);

        menuItemBorrarMantenimientoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397535117_minus_remove_green.png"))); // NOI18N
        menuItemBorrarMantenimientoProyectos.setText("Borrar");
        menuItemBorrarMantenimientoProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemBorrarMantenimientoProyectosActionPerformed(evt);
            }
        });
        menuMantenimientoProyectos.add(menuItemBorrarMantenimientoProyectos);

        menuItemCrearMantenimientoProyectos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397533314_plus_add_blue.png"))); // NOI18N
        menuItemCrearMantenimientoProyectos.setText("Crear");
        menuItemCrearMantenimientoProyectos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearMantenimientoProyectosActionPerformed(evt);
            }
        });
        menuMantenimientoProyectos.add(menuItemCrearMantenimientoProyectos);

        menuProyectos.add(menuMantenimientoProyectos);

        menuBar1.add(menuProyectos);

        menuTareas.setText("Tareas");

        menuItemConsultaTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397543922_xmag.png"))); // NOI18N
        menuItemConsultaTareas.setText("Consulta");
        menuItemConsultaTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaTareasActionPerformed(evt);
            }
        });
        menuTareas.add(menuItemConsultaTareas);

        menuMantenimientoTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550416_maintenance.png"))); // NOI18N
        menuMantenimientoTareas.setText("Mantenimiento");

        menuItemActualizarMantenimientoTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397534265_earth_internet_reload.png"))); // NOI18N
        menuItemActualizarMantenimientoTareas.setText("Actualizar");
        menuItemActualizarMantenimientoTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarMantenimientoTareasActionPerformed(evt);
            }
        });
        menuMantenimientoTareas.add(menuItemActualizarMantenimientoTareas);

        menuItemCrearMantenimientoTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397533314_plus_add_blue.png"))); // NOI18N
        menuItemCrearMantenimientoTareas.setText("Crear");
        menuItemCrearMantenimientoTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearMantenimientoTareasActionPerformed(evt);
            }
        });
        menuMantenimientoTareas.add(menuItemCrearMantenimientoTareas);

        menuItemRenombrarMantenimientoTareas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397539638_interact.png"))); // NOI18N
        menuItemRenombrarMantenimientoTareas.setText("Renombrar");
        menuItemRenombrarMantenimientoTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRenombrarMantenimientoTareasActionPerformed(evt);
            }
        });
        menuMantenimientoTareas.add(menuItemRenombrarMantenimientoTareas);

        menuTareas.add(menuMantenimientoTareas);

        menuBar1.add(menuTareas);

        menuIssues.setText("Issues");

        menuItemConsultaIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397543922_xmag.png"))); // NOI18N
        menuItemConsultaIssues.setText("Consulta");
        menuItemConsultaIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaIssuesActionPerformed(evt);
            }
        });
        menuIssues.add(menuItemConsultaIssues);

        menuMantenimientoIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397550416_maintenance.png"))); // NOI18N
        menuMantenimientoIssues.setText("Mantenimiento");

        menuItemActualizarMantenimientoIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397534265_earth_internet_reload.png"))); // NOI18N
        menuItemActualizarMantenimientoIssues.setText("Actualizar");
        menuItemActualizarMantenimientoIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemActualizarMantenimientoIssuesActionPerformed(evt);
            }
        });
        menuMantenimientoIssues.add(menuItemActualizarMantenimientoIssues);

        menuItemCrearMantenimientoIssues.setIcon(new javax.swing.ImageIcon(getClass().getResource("/QATracker/imagenes/1397533314_plus_add_blue.png"))); // NOI18N
        menuItemCrearMantenimientoIssues.setText("Crear");
        menuItemCrearMantenimientoIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemCrearMantenimientoIssuesActionPerformed(evt);
            }
        });
        menuMantenimientoIssues.add(menuItemCrearMantenimientoIssues);

        menuIssues.add(menuMantenimientoIssues);

        menuBar1.add(menuIssues);

        menuSesion.setBackground(new java.awt.Color(0, 255, 204));
        menuSesion.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        menuSesion.setForeground(new java.awt.Color(0, 153, 153));
        menuSesion.setText("DEFAULT");
        menuBar1.add(menuSesion);

        setJMenuBar(menuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemExitActionPerformed

    private void menuItemLogInInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemLogInInicioActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()==null) {
                LogIn login= new LogIn();
                login.setVisible(true);
                login.setTitle("Iniciar Sesion");
                login.setClosable(true);
                login.setMaximizable(true);
                login.setResizable(true);
                jDesktopPane1.add(login);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Ya hay una sesion activa.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemLogInInicioActionPerformed

    private void menuItemActualizrMantenimientoProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizrMantenimientoProyectosActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) {   
                ActualizarProyecto actualizar= new ActualizarProyecto();
                actualizar.setVisible(true);
                actualizar.setTitle("Actualizar Proyecto");
                actualizar.setMaximizable(true);
                actualizar.setClosable(true);
                actualizar.setResizable(true);
                jDesktopPane1.add(actualizar);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(QATracker.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_menuItemActualizrMantenimientoProyectosActionPerformed

    private void menuItemCrearMantenimientoProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearMantenimientoProyectosActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) {
                CrearProyecto crear= new CrearProyecto();
                crear.setVisible(true);
                crear.setTitle("Crear Proyecto");
                crear.setResizable(true);
                crear.setClosable(true);
                crear.setMaximizable(true);
                jDesktopPane1.add(crear);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemCrearMantenimientoProyectosActionPerformed

    private void menuItemBorrarMantenimientoProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemBorrarMantenimientoProyectosActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null){
                BorrarProyecto borrar= new BorrarProyecto();
                borrar.setVisible(true);
                borrar.setTitle("Borrar Proyecto");
                borrar.setClosable(true);
                borrar.setMaximizable(true);
                borrar.setResizable(true);
                jDesktopPane1.add(borrar);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemBorrarMantenimientoProyectosActionPerformed

    private void menuItemActualizarMantenimientoTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarMantenimientoTareasActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) { 
                ActualizarTarea actualizar= new ActualizarTarea();
                actualizar.setVisible(true);
                actualizar.setTitle("Actualizar Tarea");
                actualizar.setClosable(true);
                actualizar.setMaximizable(true);
                actualizar.setResizable(true);
                jDesktopPane1.add(actualizar);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemActualizarMantenimientoTareasActionPerformed

    private void menuItemCrearMantenimientoTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearMantenimientoTareasActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) {     
                CrearTarea crear= new CrearTarea();
                crear.setVisible(true);
                crear.setTitle("Crear Tarea");
                crear.setClosable(true);
                crear.setMaximizable(true);
                crear.setResizable(true);
                jDesktopPane1.add(crear);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);            
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemCrearMantenimientoTareasActionPerformed

    private void menuItemRenombrarMantenimientoTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRenombrarMantenimientoTareasActionPerformed
        try {
            // TODO add your handling code here:
            if (usuarioBus.getUsuarioActual()!=null) {        
                RenombrarTarea rename= new RenombrarTarea();
                rename.setVisible(true);
                rename.setTitle("Renombrar Tarea");
                rename.setClosable(true);
                rename.setMaximizable(true);
                rename.setResizable(true);
                jDesktopPane1.add(rename);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemRenombrarMantenimientoTareasActionPerformed

    private void menuItemActualizarMantenimientoIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemActualizarMantenimientoIssuesActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) {
                ActualizarIssues actualizar= new ActualizarIssues();
                actualizar.setVisible(true);
                actualizar.setTitle("Actualizar Issue");
                actualizar.setClosable(true);
                actualizar.setMaximizable(true);
                actualizar.setResizable(true);
                jDesktopPane1.add(actualizar);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la region de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_menuItemActualizarMantenimientoIssuesActionPerformed

    private void menuItemCrearMantenimientoIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemCrearMantenimientoIssuesActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) {    
                CrearIssue crear= new CrearIssue();
                crear.setVisible(true);
                crear.setTitle("Crear Issue");
                crear.setClosable(true);
                crear.setMaximizable(true);
                crear.setResizable(true);
                jDesktopPane1.add(crear);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Debe iniciar sesion en la reigon de inicio.", "Sesion Inactiva", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemCrearMantenimientoIssuesActionPerformed

    private void menuItemSignOutInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSignOutInicioActionPerformed
        try {
            if (usuarioBus.getUsuarioActual()!=null) {
               usuarioBus.signOut();
               menuSesion.setVisible(false);
               menuItemSettings.setVisible(false);
               JOptionPane.showMessageDialog(rootPane, "Se ha cerrado sesion.", "Adios!", JOptionPane.PLAIN_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "No hay niguna sesion activa.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemSignOutInicioActionPerformed

    private void menuItemConsultaProyectosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaProyectosActionPerformed
        try {      
                ConsultaProyectos consulta= new ConsultaProyectos();
                consulta.setVisible(true);
                consulta.setTitle("Proyectos");
                consulta.setClosable(true);
                consulta.setMaximizable(true);
                consulta.setResizable(true);
                jDesktopPane1.add(consulta);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemConsultaProyectosActionPerformed

    private void menuItemConsultaTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaTareasActionPerformed
        ConsultaTareas consulta= new ConsultaTareas();
        consulta.setVisible(true);
        consulta.setTitle("Tareas");
        consulta.setClosable(true);
        consulta.setMaximizable(true);
        consulta.setResizable(true);
        jDesktopPane1.add(consulta);
    }//GEN-LAST:event_menuItemConsultaTareasActionPerformed

    private void menuItemConsultaIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaIssuesActionPerformed
        // TODO add your handling code here:
        ConsultaIssues consulta= new ConsultaIssues();
        consulta.setVisible(true);
        consulta.setClosable(true);
        consulta.setMaximizable(true);
        consulta.setResizable(true);
        consulta.setTitle("Issues");
        jDesktopPane1.add(consulta);
    }//GEN-LAST:event_menuItemConsultaIssuesActionPerformed

    private void menuItemSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemSettingsActionPerformed
        try {
            // TODO add your handling code here:
            Settings settings= new Settings();
            settings.setVisible(true);
            settings.setClosable(true);
            settings.setMaximizable(true);
            settings.setTitle("Settings");
            settings.setResizable(true);
            jDesktopPane1.add(settings);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_menuItemSettingsActionPerformed

    private void menuItemNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNewUserActionPerformed
        // TODO add your handling code here:
        CrearUsuario crear= new CrearUsuario();
        crear.setClosable(true);
        crear.setVisible(true);
        crear.setTitle("Nuevo Usuario");
        jDesktopPane1.add(crear);
    }//GEN-LAST:event_menuItemNewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QATracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QATracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QATracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QATracker.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new QATracker().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(QATracker.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenuBar menuBar1;
    private javax.swing.JMenu menuIssues;
    private javax.swing.JMenuItem menuItemActualizarMantenimientoIssues;
    private javax.swing.JMenuItem menuItemActualizarMantenimientoTareas;
    private javax.swing.JMenuItem menuItemActualizrMantenimientoProyectos;
    private javax.swing.JMenuItem menuItemBorrarMantenimientoProyectos;
    private javax.swing.JMenuItem menuItemConsultaIssues;
    private javax.swing.JMenuItem menuItemConsultaProyectos;
    private javax.swing.JMenuItem menuItemConsultaTareas;
    private javax.swing.JMenuItem menuItemCrearMantenimientoIssues;
    private javax.swing.JMenuItem menuItemCrearMantenimientoProyectos;
    private javax.swing.JMenuItem menuItemCrearMantenimientoTareas;
    private javax.swing.JMenuItem menuItemExit;
    private javax.swing.JMenuItem menuItemLogInInicio;
    private javax.swing.JMenuItem menuItemNewUser;
    private javax.swing.JMenuItem menuItemRenombrarMantenimientoTareas;
    public static javax.swing.JMenuItem menuItemSettings;
    private javax.swing.JMenuItem menuItemSignOutInicio;
    private javax.swing.JMenu menuMantenimientoIssues;
    private javax.swing.JMenu menuMantenimientoProyectos;
    private javax.swing.JMenu menuMantenimientoTareas;
    private javax.swing.JMenu menuProyectos;
    public static javax.swing.JMenu menuSesion;
    private javax.swing.JMenu menuStart;
    private javax.swing.JMenu menuTareas;
    private javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
