/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package QATracker.view;

import QATracker.domain.Tarea;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Michelle
 */
public class RenombrarTarea extends javax.swing.JInternalFrame {

    /**
     * Creates new form RenombrarTarea
     */
    public RenombrarTarea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbIdTarea = new javax.swing.JLabel();
        lbNuevoNombre = new javax.swing.JLabel();
        txtIdTarea = new javax.swing.JTextField();
        txtNuevoNombre = new javax.swing.JTextField();
        btRenombrar = new javax.swing.JButton();

        lbIdTarea.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lbIdTarea.setForeground(new java.awt.Color(0, 51, 255));
        lbIdTarea.setText("Id Tarea:");

        lbNuevoNombre.setFont(new java.awt.Font("Bookman Old Style", 0, 14)); // NOI18N
        lbNuevoNombre.setText("Nueva Descripcion:");

        btRenombrar.setText("Renombrar");
        btRenombrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRenombrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNuevoNombre)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(btRenombrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbIdTarea)
                        .addGap(102, 102, 102)
                        .addComponent(txtIdTarea, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbIdTarea)
                    .addComponent(txtIdTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNuevoNombre)
                    .addComponent(txtNuevoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btRenombrar)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btRenombrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRenombrarActionPerformed
        try {
            // TODO add your handling code here:
            Tarea tarea= new Tarea();
            tarea.setIdTarea(Integer.parseInt(txtIdTarea.getText()));
            tarea.setDescripcionTarea(txtNuevoNombre.getText());
            QATracker.tareaBus.renombrar(tarea);
            JOptionPane.showMessageDialog(rootPane, "La tarea ha sido renombrada.", "Exito", JOptionPane.OK_OPTION);
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
        this.setVisible(false);
    }//GEN-LAST:event_btRenombrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btRenombrar;
    private javax.swing.JLabel lbIdTarea;
    private javax.swing.JLabel lbNuevoNombre;
    private javax.swing.JTextField txtIdTarea;
    private javax.swing.JTextField txtNuevoNombre;
    // End of variables declaration//GEN-END:variables
}
